### ISSUE TITLE
Padronizar Data

### ISSUE THREAD

**Issue by lucabfelix** [marquesds/damnboleto#10]
@marquesds Lucas, você não acha melhor que o retorno da data seja idêntico ao do boleto:
Dia/Mês/Ano ? Esse padrão é universal. No estado atual está Ano/Mês/Dia. Acho que devemos deixar idêntico ao do boleto e manter esse padrão.

**Comment by marquesds** [comment]
@felixltda, não. É uma boa prática manter no padrão ISO; não vamos mudar.
Ref.: https://en.wikipedia.org/wiki/ISO_8601
