### ISSUE TITLE
Corrigir a quantidade de casas decimais do montante

### ISSUE THREAD

**Issue by lucabfelix** [marquesds/damnboleto#12]
@marquesds A quantidade de casas decimais do montante está errada. Por exemplo: Um boleto com o montante de duzentos reais precisa retornar duas casa decimais, assim: 200,00. No estado atual está retornando apenas uma casa decimal, assim: 200,0. Acho que devemos corrigir isso.

**Comment by marquesds** [comment]
Está correto. Se for melhorar, é recomendado mostrar os valores em centavos, para facilitar a conta. Mas farei em outro momento.
